name: Dove

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  provider: ^6.0.0
  serializable: any
 cupertino_icons: ^1.0.2
  http: ^0.13.4
  geolocator: ^8.0.1
  protobuf: ^2.0.1
  image_picker: any
  geocode: 1.0.1
  proj4dart: any
  cached_network_image: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
