// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_schema.proto

package messageschema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequestData struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequestData) Reset()         { *m = LoginRequestData{} }
func (m *LoginRequestData) String() string { return proto.CompactTextString(m) }
func (*LoginRequestData) ProtoMessage()    {}
func (*LoginRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{0}
}

func (m *LoginRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequestData.Unmarshal(m, b)
}
func (m *LoginRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequestData.Marshal(b, m, deterministic)
}
func (m *LoginRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequestData.Merge(m, src)
}
func (m *LoginRequestData) XXX_Size() int {
	return xxx_messageInfo_LoginRequestData.Size(m)
}
func (m *LoginRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequestData proto.InternalMessageInfo

func (m *LoginRequestData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequestData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponseData struct {
	AuthToken            string    `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	User                 *UserData `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResponseData) Reset()         { *m = LoginResponseData{} }
func (m *LoginResponseData) String() string { return proto.CompactTextString(m) }
func (*LoginResponseData) ProtoMessage()    {}
func (*LoginResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{1}
}

func (m *LoginResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponseData.Unmarshal(m, b)
}
func (m *LoginResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponseData.Marshal(b, m, deterministic)
}
func (m *LoginResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponseData.Merge(m, src)
}
func (m *LoginResponseData) XXX_Size() int {
	return xxx_messageInfo_LoginResponseData.Size(m)
}
func (m *LoginResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponseData proto.InternalMessageInfo

func (m *LoginResponseData) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *LoginResponseData) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterRequestData struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequestData) Reset()         { *m = RegisterRequestData{} }
func (m *RegisterRequestData) String() string { return proto.CompactTextString(m) }
func (*RegisterRequestData) ProtoMessage()    {}
func (*RegisterRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{2}
}

func (m *RegisterRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequestData.Unmarshal(m, b)
}
func (m *RegisterRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequestData.Marshal(b, m, deterministic)
}
func (m *RegisterRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequestData.Merge(m, src)
}
func (m *RegisterRequestData) XXX_Size() int {
	return xxx_messageInfo_RegisterRequestData.Size(m)
}
func (m *RegisterRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequestData proto.InternalMessageInfo

func (m *RegisterRequestData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequestData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponseData struct {
	AuthToken            string    `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	User                 *UserData `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterResponseData) Reset()         { *m = RegisterResponseData{} }
func (m *RegisterResponseData) String() string { return proto.CompactTextString(m) }
func (*RegisterResponseData) ProtoMessage()    {}
func (*RegisterResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{3}
}

func (m *RegisterResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponseData.Unmarshal(m, b)
}
func (m *RegisterResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponseData.Marshal(b, m, deterministic)
}
func (m *RegisterResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponseData.Merge(m, src)
}
func (m *RegisterResponseData) XXX_Size() int {
	return xxx_messageInfo_RegisterResponseData.Size(m)
}
func (m *RegisterResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponseData proto.InternalMessageInfo

func (m *RegisterResponseData) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *RegisterResponseData) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

type ImageData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageData) Reset()         { *m = ImageData{} }
func (m *ImageData) String() string { return proto.CompactTextString(m) }
func (*ImageData) ProtoMessage()    {}
func (*ImageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{4}
}

func (m *ImageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageData.Unmarshal(m, b)
}
func (m *ImageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageData.Marshal(b, m, deterministic)
}
func (m *ImageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageData.Merge(m, src)
}
func (m *ImageData) XXX_Size() int {
	return xxx_messageInfo_ImageData.Size(m)
}
func (m *ImageData) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageData.DiscardUnknown(m)
}

var xxx_messageInfo_ImageData proto.InternalMessageInfo

func (m *ImageData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type NewFeaturePointRequestData struct {
	Title                string        `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location             *LocationData `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Images               []*ImageData  `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NewFeaturePointRequestData) Reset()         { *m = NewFeaturePointRequestData{} }
func (m *NewFeaturePointRequestData) String() string { return proto.CompactTextString(m) }
func (*NewFeaturePointRequestData) ProtoMessage()    {}
func (*NewFeaturePointRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{5}
}

func (m *NewFeaturePointRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewFeaturePointRequestData.Unmarshal(m, b)
}
func (m *NewFeaturePointRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewFeaturePointRequestData.Marshal(b, m, deterministic)
}
func (m *NewFeaturePointRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewFeaturePointRequestData.Merge(m, src)
}
func (m *NewFeaturePointRequestData) XXX_Size() int {
	return xxx_messageInfo_NewFeaturePointRequestData.Size(m)
}
func (m *NewFeaturePointRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewFeaturePointRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_NewFeaturePointRequestData proto.InternalMessageInfo

func (m *NewFeaturePointRequestData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewFeaturePointRequestData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewFeaturePointRequestData) GetLocation() *LocationData {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *NewFeaturePointRequestData) GetImages() []*ImageData {
	if m != nil {
		return m.Images
	}
	return nil
}

type NewFeaturePointResponseData struct {
	FeaturePoint         *FeaturePointData `protobuf:"bytes,1,opt,name=feature_point,json=featurePoint,proto3" json:"feature_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewFeaturePointResponseData) Reset()         { *m = NewFeaturePointResponseData{} }
func (m *NewFeaturePointResponseData) String() string { return proto.CompactTextString(m) }
func (*NewFeaturePointResponseData) ProtoMessage()    {}
func (*NewFeaturePointResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{6}
}

func (m *NewFeaturePointResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewFeaturePointResponseData.Unmarshal(m, b)
}
func (m *NewFeaturePointResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewFeaturePointResponseData.Marshal(b, m, deterministic)
}
func (m *NewFeaturePointResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewFeaturePointResponseData.Merge(m, src)
}
func (m *NewFeaturePointResponseData) XXX_Size() int {
	return xxx_messageInfo_NewFeaturePointResponseData.Size(m)
}
func (m *NewFeaturePointResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewFeaturePointResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_NewFeaturePointResponseData proto.InternalMessageInfo

func (m *NewFeaturePointResponseData) GetFeaturePoint() *FeaturePointData {
	if m != nil {
		return m.FeaturePoint
	}
	return nil
}

type LocationData struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationData) Reset()         { *m = LocationData{} }
func (m *LocationData) String() string { return proto.CompactTextString(m) }
func (*LocationData) ProtoMessage()    {}
func (*LocationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{7}
}

func (m *LocationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationData.Unmarshal(m, b)
}
func (m *LocationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationData.Marshal(b, m, deterministic)
}
func (m *LocationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationData.Merge(m, src)
}
func (m *LocationData) XXX_Size() int {
	return xxx_messageInfo_LocationData.Size(m)
}
func (m *LocationData) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationData.DiscardUnknown(m)
}

var xxx_messageInfo_LocationData proto.InternalMessageInfo

func (m *LocationData) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LocationData) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type FeaturePointData struct {
	FeaturePointId       int64                    `protobuf:"varint,1,opt,name=feature_point_id,json=featurePointId,proto3" json:"feature_point_id,omitempty"`
	Title                string                   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location             *LocationData            `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	OwnerId              int64                    `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt            int64                    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Images               []*FeaturePointImageData `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FeaturePointData) Reset()         { *m = FeaturePointData{} }
func (m *FeaturePointData) String() string { return proto.CompactTextString(m) }
func (*FeaturePointData) ProtoMessage()    {}
func (*FeaturePointData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{8}
}

func (m *FeaturePointData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeaturePointData.Unmarshal(m, b)
}
func (m *FeaturePointData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeaturePointData.Marshal(b, m, deterministic)
}
func (m *FeaturePointData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeaturePointData.Merge(m, src)
}
func (m *FeaturePointData) XXX_Size() int {
	return xxx_messageInfo_FeaturePointData.Size(m)
}
func (m *FeaturePointData) XXX_DiscardUnknown() {
	xxx_messageInfo_FeaturePointData.DiscardUnknown(m)
}

var xxx_messageInfo_FeaturePointData proto.InternalMessageInfo

func (m *FeaturePointData) GetFeaturePointId() int64 {
	if m != nil {
		return m.FeaturePointId
	}
	return 0
}

func (m *FeaturePointData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FeaturePointData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FeaturePointData) GetLocation() *LocationData {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *FeaturePointData) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *FeaturePointData) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FeaturePointData) GetImages() []*FeaturePointImageData {
	if m != nil {
		return m.Images
	}
	return nil
}

type FeaturePointImageData struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                *NetworkImageData `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FeaturePointImageData) Reset()         { *m = FeaturePointImageData{} }
func (m *FeaturePointImageData) String() string { return proto.CompactTextString(m) }
func (*FeaturePointImageData) ProtoMessage()    {}
func (*FeaturePointImageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{9}
}

func (m *FeaturePointImageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeaturePointImageData.Unmarshal(m, b)
}
func (m *FeaturePointImageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeaturePointImageData.Marshal(b, m, deterministic)
}
func (m *FeaturePointImageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeaturePointImageData.Merge(m, src)
}
func (m *FeaturePointImageData) XXX_Size() int {
	return xxx_messageInfo_FeaturePointImageData.Size(m)
}
func (m *FeaturePointImageData) XXX_DiscardUnknown() {
	xxx_messageInfo_FeaturePointImageData.DiscardUnknown(m)
}

var xxx_messageInfo_FeaturePointImageData proto.InternalMessageInfo

func (m *FeaturePointImageData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeaturePointImageData) GetImage() *NetworkImageData {
	if m != nil {
		return m.Image
	}
	return nil
}

type NetworkImageData struct {
	LocalPath            string   `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkImageData) Reset()         { *m = NetworkImageData{} }
func (m *NetworkImageData) String() string { return proto.CompactTextString(m) }
func (*NetworkImageData) ProtoMessage()    {}
func (*NetworkImageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{10}
}

func (m *NetworkImageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkImageData.Unmarshal(m, b)
}
func (m *NetworkImageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkImageData.Marshal(b, m, deterministic)
}
func (m *NetworkImageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkImageData.Merge(m, src)
}
func (m *NetworkImageData) XXX_Size() int {
	return xxx_messageInfo_NetworkImageData.Size(m)
}
func (m *NetworkImageData) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkImageData.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkImageData proto.InternalMessageInfo

func (m *NetworkImageData) GetLocalPath() string {
	if m != nil {
		return m.LocalPath
	}
	return ""
}

type UpdateFeaturePointRequestData struct {
	Id                   int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Uploaded             []*ImageData             `protobuf:"bytes,4,rep,name=uploaded,proto3" json:"uploaded,omitempty"`
	Deleted              []*FeaturePointImageData `protobuf:"bytes,5,rep,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UpdateFeaturePointRequestData) Reset()         { *m = UpdateFeaturePointRequestData{} }
func (m *UpdateFeaturePointRequestData) String() string { return proto.CompactTextString(m) }
func (*UpdateFeaturePointRequestData) ProtoMessage()    {}
func (*UpdateFeaturePointRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{11}
}

func (m *UpdateFeaturePointRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeaturePointRequestData.Unmarshal(m, b)
}
func (m *UpdateFeaturePointRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeaturePointRequestData.Marshal(b, m, deterministic)
}
func (m *UpdateFeaturePointRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeaturePointRequestData.Merge(m, src)
}
func (m *UpdateFeaturePointRequestData) XXX_Size() int {
	return xxx_messageInfo_UpdateFeaturePointRequestData.Size(m)
}
func (m *UpdateFeaturePointRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeaturePointRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeaturePointRequestData proto.InternalMessageInfo

func (m *UpdateFeaturePointRequestData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateFeaturePointRequestData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateFeaturePointRequestData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateFeaturePointRequestData) GetUploaded() []*ImageData {
	if m != nil {
		return m.Uploaded
	}
	return nil
}

func (m *UpdateFeaturePointRequestData) GetDeleted() []*FeaturePointImageData {
	if m != nil {
		return m.Deleted
	}
	return nil
}

type UpdateFeaturePointResponseData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFeaturePointResponseData) Reset()         { *m = UpdateFeaturePointResponseData{} }
func (m *UpdateFeaturePointResponseData) String() string { return proto.CompactTextString(m) }
func (*UpdateFeaturePointResponseData) ProtoMessage()    {}
func (*UpdateFeaturePointResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{12}
}

func (m *UpdateFeaturePointResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeaturePointResponseData.Unmarshal(m, b)
}
func (m *UpdateFeaturePointResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeaturePointResponseData.Marshal(b, m, deterministic)
}
func (m *UpdateFeaturePointResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeaturePointResponseData.Merge(m, src)
}
func (m *UpdateFeaturePointResponseData) XXX_Size() int {
	return xxx_messageInfo_UpdateFeaturePointResponseData.Size(m)
}
func (m *UpdateFeaturePointResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeaturePointResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeaturePointResponseData proto.InternalMessageInfo

type GetAllFeaturePointsWithinBoundsResponseData struct {
	FeaturePoints        []*FeaturePointData `protobuf:"bytes,1,rep,name=feature_points,json=featurePoints,proto3" json:"feature_points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAllFeaturePointsWithinBoundsResponseData) Reset() {
	*m = GetAllFeaturePointsWithinBoundsResponseData{}
}
func (m *GetAllFeaturePointsWithinBoundsResponseData) String() string {
	return proto.CompactTextString(m)
}
func (*GetAllFeaturePointsWithinBoundsResponseData) ProtoMessage() {}
func (*GetAllFeaturePointsWithinBoundsResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{13}
}

func (m *GetAllFeaturePointsWithinBoundsResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllFeaturePointsWithinBoundsResponseData.Unmarshal(m, b)
}
func (m *GetAllFeaturePointsWithinBoundsResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllFeaturePointsWithinBoundsResponseData.Marshal(b, m, deterministic)
}
func (m *GetAllFeaturePointsWithinBoundsResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllFeaturePointsWithinBoundsResponseData.Merge(m, src)
}
func (m *GetAllFeaturePointsWithinBoundsResponseData) XXX_Size() int {
	return xxx_messageInfo_GetAllFeaturePointsWithinBoundsResponseData.Size(m)
}
func (m *GetAllFeaturePointsWithinBoundsResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllFeaturePointsWithinBoundsResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllFeaturePointsWithinBoundsResponseData proto.InternalMessageInfo

func (m *GetAllFeaturePointsWithinBoundsResponseData) GetFeaturePoints() []*FeaturePointData {
	if m != nil {
		return m.FeaturePoints
	}
	return nil
}

type GetUserByIdResponseData struct {
	User                 *UserData `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserByIdResponseData) Reset()         { *m = GetUserByIdResponseData{} }
func (m *GetUserByIdResponseData) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResponseData) ProtoMessage()    {}
func (*GetUserByIdResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{14}
}

func (m *GetUserByIdResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResponseData.Unmarshal(m, b)
}
func (m *GetUserByIdResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResponseData.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResponseData.Merge(m, src)
}
func (m *GetUserByIdResponseData) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResponseData.Size(m)
}
func (m *GetUserByIdResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResponseData proto.InternalMessageInfo

func (m *GetUserByIdResponseData) GetUser() *UserData {
	if m != nil {
		return m.User
	}
	return nil
}

type UserData struct {
	UserId               int64             `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	About                string            `protobuf:"bytes,3,opt,name=about,proto3" json:"about,omitempty"`
	CreatedAt            int64             `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProfileImage         *NetworkImageData `protobuf:"bytes,5,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{15}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserData) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *UserData) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserData) GetProfileImage() *NetworkImageData {
	if m != nil {
		return m.ProfileImage
	}
	return nil
}

type DeleteFeaturePointResponseData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeaturePointResponseData) Reset()         { *m = DeleteFeaturePointResponseData{} }
func (m *DeleteFeaturePointResponseData) String() string { return proto.CompactTextString(m) }
func (*DeleteFeaturePointResponseData) ProtoMessage()    {}
func (*DeleteFeaturePointResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{16}
}

func (m *DeleteFeaturePointResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeaturePointResponseData.Unmarshal(m, b)
}
func (m *DeleteFeaturePointResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeaturePointResponseData.Marshal(b, m, deterministic)
}
func (m *DeleteFeaturePointResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeaturePointResponseData.Merge(m, src)
}
func (m *DeleteFeaturePointResponseData) XXX_Size() int {
	return xxx_messageInfo_DeleteFeaturePointResponseData.Size(m)
}
func (m *DeleteFeaturePointResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeaturePointResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeaturePointResponseData proto.InternalMessageInfo

type NewProfileImageRequestData struct {
	Image                *ImageData `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NewProfileImageRequestData) Reset()         { *m = NewProfileImageRequestData{} }
func (m *NewProfileImageRequestData) String() string { return proto.CompactTextString(m) }
func (*NewProfileImageRequestData) ProtoMessage()    {}
func (*NewProfileImageRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{17}
}

func (m *NewProfileImageRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProfileImageRequestData.Unmarshal(m, b)
}
func (m *NewProfileImageRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProfileImageRequestData.Marshal(b, m, deterministic)
}
func (m *NewProfileImageRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProfileImageRequestData.Merge(m, src)
}
func (m *NewProfileImageRequestData) XXX_Size() int {
	return xxx_messageInfo_NewProfileImageRequestData.Size(m)
}
func (m *NewProfileImageRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProfileImageRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_NewProfileImageRequestData proto.InternalMessageInfo

func (m *NewProfileImageRequestData) GetImage() *ImageData {
	if m != nil {
		return m.Image
	}
	return nil
}

type NewProfileImageResponseData struct {
	Image                *NetworkImageData `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewProfileImageResponseData) Reset()         { *m = NewProfileImageResponseData{} }
func (m *NewProfileImageResponseData) String() string { return proto.CompactTextString(m) }
func (*NewProfileImageResponseData) ProtoMessage()    {}
func (*NewProfileImageResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{18}
}

func (m *NewProfileImageResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProfileImageResponseData.Unmarshal(m, b)
}
func (m *NewProfileImageResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProfileImageResponseData.Marshal(b, m, deterministic)
}
func (m *NewProfileImageResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProfileImageResponseData.Merge(m, src)
}
func (m *NewProfileImageResponseData) XXX_Size() int {
	return xxx_messageInfo_NewProfileImageResponseData.Size(m)
}
func (m *NewProfileImageResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProfileImageResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_NewProfileImageResponseData proto.InternalMessageInfo

func (m *NewProfileImageResponseData) GetImage() *NetworkImageData {
	if m != nil {
		return m.Image
	}
	return nil
}

type UpdateUserProfileRequestData struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	About                string   `protobuf:"bytes,2,opt,name=about,proto3" json:"about,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserProfileRequestData) Reset()         { *m = UpdateUserProfileRequestData{} }
func (m *UpdateUserProfileRequestData) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileRequestData) ProtoMessage()    {}
func (*UpdateUserProfileRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{19}
}

func (m *UpdateUserProfileRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileRequestData.Unmarshal(m, b)
}
func (m *UpdateUserProfileRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileRequestData.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileRequestData.Merge(m, src)
}
func (m *UpdateUserProfileRequestData) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileRequestData.Size(m)
}
func (m *UpdateUserProfileRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileRequestData proto.InternalMessageInfo

func (m *UpdateUserProfileRequestData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserProfileRequestData) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

type UpdateUserProfileResponseData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserProfileResponseData) Reset()         { *m = UpdateUserProfileResponseData{} }
func (m *UpdateUserProfileResponseData) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileResponseData) ProtoMessage()    {}
func (*UpdateUserProfileResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3c8d66ffcbf096e, []int{20}
}

func (m *UpdateUserProfileResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileResponseData.Unmarshal(m, b)
}
func (m *UpdateUserProfileResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileResponseData.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileResponseData.Merge(m, src)
}
func (m *UpdateUserProfileResponseData) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileResponseData.Size(m)
}
func (m *UpdateUserProfileResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileResponseData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequestData)(nil), "messageschema.LoginRequestData")
	proto.RegisterType((*LoginResponseData)(nil), "messageschema.LoginResponseData")
	proto.RegisterType((*RegisterRequestData)(nil), "messageschema.RegisterRequestData")
	proto.RegisterType((*RegisterResponseData)(nil), "messageschema.RegisterResponseData")
	proto.RegisterType((*ImageData)(nil), "messageschema.ImageData")
	proto.RegisterType((*NewFeaturePointRequestData)(nil), "messageschema.NewFeaturePointRequestData")
	proto.RegisterType((*NewFeaturePointResponseData)(nil), "messageschema.NewFeaturePointResponseData")
	proto.RegisterType((*LocationData)(nil), "messageschema.LocationData")
	proto.RegisterType((*FeaturePointData)(nil), "messageschema.FeaturePointData")
	proto.RegisterType((*FeaturePointImageData)(nil), "messageschema.FeaturePointImageData")
	proto.RegisterType((*NetworkImageData)(nil), "messageschema.NetworkImageData")
	proto.RegisterType((*UpdateFeaturePointRequestData)(nil), "messageschema.UpdateFeaturePointRequestData")
	proto.RegisterType((*UpdateFeaturePointResponseData)(nil), "messageschema.UpdateFeaturePointResponseData")
	proto.RegisterType((*GetAllFeaturePointsWithinBoundsResponseData)(nil), "messageschema.GetAllFeaturePointsWithinBoundsResponseData")
	proto.RegisterType((*GetUserByIdResponseData)(nil), "messageschema.GetUserByIdResponseData")
	proto.RegisterType((*UserData)(nil), "messageschema.UserData")
	proto.RegisterType((*DeleteFeaturePointResponseData)(nil), "messageschema.DeleteFeaturePointResponseData")
	proto.RegisterType((*NewProfileImageRequestData)(nil), "messageschema.NewProfileImageRequestData")
	proto.RegisterType((*NewProfileImageResponseData)(nil), "messageschema.NewProfileImageResponseData")
	proto.RegisterType((*UpdateUserProfileRequestData)(nil), "messageschema.UpdateUserProfileRequestData")
	proto.RegisterType((*UpdateUserProfileResponseData)(nil), "messageschema.UpdateUserProfileResponseData")
}

func init() { proto.RegisterFile("message_schema.proto", fileDescriptor_f3c8d66ffcbf096e) }

var fileDescriptor_f3c8d66ffcbf096e = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6a, 0xdb, 0x4a,
	0x10, 0x46, 0xf2, 0xff, 0xd8, 0x0e, 0x3e, 0x7b, 0x7c, 0x88, 0x4f, 0x7e, 0x4e, 0x8c, 0x38, 0x17,
	0x81, 0x80, 0x69, 0xd3, 0x86, 0xde, 0x94, 0x42, 0x82, 0x49, 0xea, 0x92, 0x06, 0x23, 0x12, 0x7a,
	0x57, 0xb1, 0xf1, 0x4e, 0x6c, 0x11, 0x59, 0xab, 0x6a, 0x57, 0x98, 0x3e, 0x50, 0x5f, 0xa2, 0x37,
	0x7d, 0x92, 0xbe, 0x4b, 0xd9, 0x95, 0x64, 0x4b, 0xca, 0x9f, 0x5b, 0xda, 0xbb, 0xec, 0xcc, 0xee,
	0xa7, 0x6f, 0xe6, 0x9b, 0x6f, 0x62, 0xe8, 0xce, 0x51, 0x08, 0x3a, 0x45, 0x47, 0x4c, 0x66, 0x38,
	0xa7, 0x83, 0x20, 0xe4, 0x92, 0x93, 0x76, 0x12, 0x8d, 0x83, 0xd6, 0x3b, 0xe8, 0x9c, 0xf3, 0xa9,
	0xeb, 0xdb, 0xf8, 0x29, 0x42, 0x21, 0x87, 0x54, 0x52, 0xb2, 0x05, 0xf5, 0x48, 0x60, 0xe8, 0xd3,
	0x39, 0xf6, 0x8c, 0xbe, 0xb1, 0xdf, 0xb0, 0x97, 0x67, 0x95, 0x0b, 0xa8, 0x10, 0x0b, 0x1e, 0xb2,
	0x9e, 0x19, 0xe7, 0xd2, 0xb3, 0xe5, 0xc0, 0x5f, 0x09, 0x96, 0x08, 0xb8, 0x2f, 0x50, 0x83, 0xed,
	0x02, 0xd0, 0x48, 0xce, 0x1c, 0xc9, 0x6f, 0xd1, 0x4f, 0xe0, 0x1a, 0x2a, 0x72, 0xa9, 0x02, 0xe4,
	0x00, 0xca, 0x0a, 0x5b, 0x63, 0x35, 0x0f, 0x37, 0x07, 0x39, 0x76, 0x83, 0x2b, 0x81, 0xa1, 0x42,
	0xb1, 0xf5, 0x25, 0xeb, 0x3d, 0xfc, 0x6d, 0xe3, 0xd4, 0x15, 0x12, 0xc3, 0xdf, 0xc1, 0xf7, 0x1a,
	0xba, 0x2b, 0xb8, 0x3f, 0x44, 0x79, 0x0f, 0x1a, 0xa3, 0x39, 0x9d, 0xc6, 0xc0, 0x04, 0xca, 0x8c,
	0x4a, 0xaa, 0x21, 0x5b, 0xb6, 0xfe, 0xdb, 0xfa, 0x66, 0xc0, 0xd6, 0x05, 0x2e, 0x4e, 0x91, 0xca,
	0x28, 0xc4, 0x31, 0x77, 0x7d, 0x99, 0xad, 0xad, 0x0b, 0x15, 0xe9, 0x4a, 0x2f, 0x2d, 0x2c, 0x3e,
	0x90, 0x3e, 0x34, 0x19, 0x8a, 0x49, 0xe8, 0x06, 0xd2, 0xe5, 0x7e, 0x52, 0x58, 0x36, 0x44, 0x5e,
	0x41, 0xdd, 0xe3, 0x13, 0xaa, 0xd3, 0x25, 0x4d, 0x74, 0xbb, 0x40, 0xf4, 0x3c, 0x49, 0x6b, 0xb2,
	0xcb, 0xcb, 0xe4, 0x19, 0x54, 0x5d, 0x45, 0x58, 0xf4, 0xca, 0xfd, 0xd2, 0x7e, 0xf3, 0xb0, 0x57,
	0x78, 0xb6, 0xac, 0xc6, 0x4e, 0xee, 0x59, 0x13, 0xd8, 0xbe, 0x53, 0x40, 0xa6, 0x9b, 0x43, 0x68,
	0xdf, 0xc4, 0x39, 0x27, 0x50, 0x49, 0x5d, 0x49, 0xf3, 0x70, 0xaf, 0x80, 0x9b, 0x7d, 0xaf, 0xe1,
	0x5b, 0x37, 0x99, 0x88, 0xf5, 0x16, 0x5a, 0x59, 0xc2, 0x4a, 0x57, 0x8f, 0x4a, 0x57, 0x46, 0x2c,
	0x6e, 0x8d, 0x61, 0x2f, 0xcf, 0x64, 0x07, 0x1a, 0x1e, 0xf7, 0xa7, 0x71, 0xd2, 0xd4, 0xc9, 0x55,
	0xc0, 0xfa, 0x62, 0x42, 0xa7, 0xf8, 0x31, 0xb2, 0x0f, 0x9d, 0x1c, 0x49, 0xc7, 0x65, 0x1a, 0xb6,
	0x64, 0x6f, 0x64, 0x69, 0x8c, 0xd8, 0x4a, 0x10, 0xf3, 0x11, 0x41, 0x4a, 0x8f, 0x0b, 0x52, 0xfe,
	0x19, 0x41, 0xfe, 0x85, 0x3a, 0x5f, 0xf8, 0x18, 0x2a, 0x4a, 0x15, 0x4d, 0xa9, 0xa6, 0xcf, 0x23,
	0xa6, 0x06, 0x75, 0x12, 0x22, 0x95, 0xc8, 0x1c, 0x2a, 0x7b, 0x55, 0x9d, 0x6c, 0x24, 0x91, 0x63,
	0x49, 0x5e, 0x2f, 0xa5, 0xac, 0x69, 0x29, 0xff, 0x7f, 0xa4, 0xe5, 0x77, 0x65, 0xfd, 0x08, 0xff,
	0xdc, 0x7b, 0x81, 0x6c, 0x80, 0x99, 0x74, 0xa7, 0x62, 0x9b, 0x2e, 0x23, 0x47, 0x50, 0xd1, 0x4f,
	0x12, 0x43, 0x14, 0x85, 0xbd, 0x40, 0xb9, 0xe0, 0xe1, 0xed, 0xea, 0x03, 0xf1, 0x6d, 0xeb, 0x39,
	0x74, 0x8a, 0x29, 0x55, 0x90, 0xaa, 0xdb, 0x73, 0x02, 0x2a, 0x67, 0xa9, 0xf3, 0x74, 0x64, 0x4c,
	0xe5, 0xcc, 0xfa, 0x6e, 0xc0, 0xee, 0x55, 0xc0, 0xa8, 0xc4, 0x87, 0xec, 0x52, 0xe4, 0xf6, 0xab,
	0x6a, 0xbd, 0x84, 0x7a, 0x14, 0x78, 0x9c, 0x32, 0x64, 0x4f, 0xfa, 0x60, 0x79, 0x93, 0xbc, 0x81,
	0x1a, 0x43, 0x0f, 0x25, 0x2a, 0xa5, 0xd6, 0xef, 0x78, 0xfa, 0xc8, 0xea, 0xc3, 0x7f, 0xf7, 0x95,
	0xb7, 0x32, 0x93, 0x15, 0xc1, 0xc1, 0x19, 0xca, 0x63, 0xcf, 0xcb, 0xde, 0x10, 0x1f, 0x5c, 0x39,
	0x73, 0xfd, 0x13, 0x1e, 0xf9, 0x4c, 0xe4, 0xbc, 0x77, 0x0a, 0x1b, 0xb9, 0xb1, 0x16, 0x3d, 0x43,
	0xf3, 0x7a, 0xd2, 0x7c, 0xed, 0xec, 0xd4, 0x0b, 0xeb, 0x14, 0x36, 0xcf, 0x50, 0xaa, 0xd5, 0x76,
	0xf2, 0x79, 0xc4, 0x72, 0x9f, 0x48, 0xb7, 0xa1, 0xb1, 0xce, 0x36, 0xfc, 0x6a, 0x40, 0x3d, 0x0d,
	0x91, 0x4d, 0xa8, 0xa9, 0xe0, 0xca, 0x6a, 0x55, 0x75, 0x1c, 0xb1, 0xdc, 0x3e, 0x37, 0x0b, 0xfb,
	0xbc, 0x0b, 0x15, 0x7a, 0xcd, 0x23, 0x99, 0x88, 0x16, 0x1f, 0x0a, 0x46, 0x28, 0x17, 0x8d, 0x30,
	0x84, 0x76, 0x10, 0xf2, 0x1b, 0xd7, 0x43, 0x27, 0x9e, 0xd4, 0xca, 0x7a, 0x93, 0xda, 0x4a, 0x5e,
	0xe9, 0x88, 0x52, 0x67, 0xa8, 0x85, 0x7a, 0x50, 0x9d, 0x73, 0xbd, 0xca, 0xc7, 0x99, 0x47, 0xd9,
	0xd9, 0x1c, 0xa4, 0x3e, 0x89, 0x5b, 0xf5, 0xf0, 0x40, 0x25, 0x06, 0xb9, 0xd4, 0x7b, 0x35, 0x8f,
	0x96, 0x69, 0xfc, 0x51, 0x1e, 0x6e, 0x5d, 0xdb, 0x8d, 0x61, 0x27, 0x9e, 0x31, 0xa5, 0x43, 0x02,
	0xbe, 0xee, 0x3f, 0xd3, 0x65, 0xf3, 0xcd, 0x4c, 0xf3, 0xad, 0xbd, 0xd4, 0x94, 0x39, 0xc4, 0x15,
	0xd3, 0xeb, 0xaa, 0xfe, 0xe5, 0xf1, 0xe2, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0xe0, 0x60,
	0xe3, 0x91, 0x08, 0x00, 0x00,
}
