server:
  addr: 127.0.0.1
  port: 8080

auth:
  jwtSecret: "example api secret"
  expiryTimeMinutes: 1440
  hashCost: 10

postgres:
  user: "<your postgres user>"
  dbname: "<database name>"
  host: "127.0.0.1"
  port: 5432
